# Generated by Django 5.0.4 on 2025-04-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the product', max_length=100, verbose_name='Name of product')),
                ('price', models.DecimalField(decimal_places=2, help_text='Enter the price of the product', max_digits=10, verbose_name='Price')),
                ('description', models.TextField(blank=True, help_text='Enter the description of the product', null=True, verbose_name='Description')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Enter the quantity of the product', verbose_name='Quantity')),
                ('ingredients', models.TextField(blank=True, help_text='Enter the ingredients of the product', null=True, verbose_name='Ingredients')),
                ('photo', models.ImageField(blank=True, help_text='Upload a photo of the product', null=True, upload_to='products/photos/', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
    ]
